/*
* Class to define String constants values for MS
*
* ********************************* Revision History ***************************
* 1. [MS-27]: Only authorized users are to add Approvers and Training Requirements
* 2. [MS-11]: CAPA Create / Edit / Detail Page
********************************** Revision History **************************/
public class CQ_MS_Constants {

    public static final String CQ_MS_ADD_APPROVERS_TRAINING_PERMISSION_SET = 'CQ_MS_Add_Approvers_Trainings',
        STANDARD_USER_PROFILE = 'Standard User',
        TEMPLATE_DOCUMENT_TYPE = 'Template_Document',
        CONTROLLED_DOCUMENT_TYPE = 'Controlled_Document',
        DOCUMENT_STATUS_CURRENT = 'Current',
        DOCUMENT_RECORD_ACTIVITY_REVISE = 'revise',
        CQ_CAPA_OWNER_PERMISSION_SET = 'CQ_CAPA_Owner',
        CAPA_TYPE_CUSTOMER = 'Customer',
        CAPA_SUBTYPE_PRODUCT_QUALITY = 'Product Quality',
        CAPA_DIVISION_HOUSTON = 'Houston',
        CAPA_PRODUCT_QUALITY_HOUSTAN_APPROVAL_MATRIX = 'CAPA - Product Quality - Houston';
        
}