#!groovy

import groovy.json.JsonSlurperClassic

node {

    // def SF_CONSUMER_KEY=env.SF_CONSUMER_KEY
    // def SF_USERNAME=env.SF_USERNAME
    def SERVER_KEY_CREDENTALS_ID=env.SERVER_KEY_CREDENTALS_ID
    //def TEST_LEVEL='RunLocalTests'
    //def PACKAGE_NAME='0Ho1U000000CaUzSAK'
    //def PACKAGE_VERSION
    def SF_INSTANCE_URL = "https://test.salesforce.com"
    def SF_CONSUMER_KEY= '3MVG9oZtFCVWuSwOgnZa__voKuQTg9L2_LLfPQbldA_5bgzpEkeo7ecAvVn2REsAPNukZeMkvnjRvCuLYHtVu'
    def SF_USERNAME= 'sophiya.maharjan@anujplayv12.com'
    def toolbelt = tool 'toolbelt'


    // -------------------------------------------------------------------------
    // Check out code from source control.
    // -------------------------------------------------------------------------

    stage('checkout source') {
        checkout scm
    }


    // -------------------------------------------------------------------------
    // Run all the enclosed stages with access to the Salesforce
    // JWT key credentials.
    // -------------------------------------------------------------------------
    
    withEnv(["HOME=${env.WORKSPACE}"]) {
        
        withCredentials([file(credentialsId: SERVER_KEY_CREDENTALS_ID, variable: 'server_key_file')]) {

            // -------------------------------------------------------------------------
            // Authorize the Dev Hub org with JWT key and give it an alias.
            // -------------------------------------------------------------------------

            stage('Authorize DevHub') {
                rc = command "${toolbelt}sfdx auth:jwt:grant --instanceurl ${SF_INSTANCE_URL} --clientid ${SF_CONSUMER_KEY} --username ${SF_USERNAME} --jwtkeyfile ${server_key_file} --setdefaultdevhubusername --setalias HubOrg"
                if (rc != 0) {
                    error 'Salesforce dev hub org authorization failed.'
                }
            }



            // -------------------------------------------------------------------------
            // Push source to Sandbox.
            // -------------------------------------------------------------------------

            stage('Push To Sandbox') {
                rc = command "${toolbelt}sfdx force:source:push --targetusername ciorg"
                if (rc != 0) {
                    error 'Salesforce push to Sandbox failed.'
                }
            }


        }
    }
}

def command(script) {
    if (isUnix()) {
        return sh(returnStatus: true, script: script);
    } else {
        return bat(returnStatus: true, script: script);
    }
}